### ISSUE TITLE
Liquidator cannot be compile sometime on AWS

### ISSUE THREAD

**Issue by leonardgee** [port-finance/liquidator#2]
```
ts-node src/partial-pyth.ts 
/home/ubuntu/liquidator/src/partial-pyth.ts:44
    const parsedData = pyth_1.parsePriceData(pythData?.data);
                                                      ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1225:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at main (/usr/local/lib/node_modules/ts-node/src/bin.ts:330:12)
```

**Comment by eternnoir** [comment]
What version of nodejs are you using? I'm having the same problem as you with v12.20.1. Updating to nodejs 14 fixed it.

**Comment by leonardgee** [comment]
I think you are right.
