### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Jin-K-Yang** [port-finance/liquidator#37]
When I run ```yarn liquidator```, I got the error
```
/root/port/src/partial.ts:202
        console.log(`name: ${portProfile.getAssetContext().findConfigByReserveId(port_sdk_1.ReserveId.fromBase58(token))?.getDisplayConfig().getName()} price: ${price.toString()}`);
                                                                                                                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (/root/port/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/root/port/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at main (/root/port/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/root/port/node_modules/ts-node/src/bin.ts:288:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Is the bug or something I miss? thanks!

**Comment by leonardgee** [comment]
Hey, which version of `tsc` and `node` are you using?
