### ISSUE TITLE
Error: failed to send transaction: Transaction simulation failed

### ISSUE THREAD

**Issue by JiaxingZhao** [port-finance/liquidator#38]
When i run liquidator with docker-compose, an error occurs：`Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.`

> Environment: 
    Ubuntu 20.04 LTS
    Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
    docker-compose version 1.25.0

```shell
ubuntu@VM-0-6-ubuntu:~/liquidator$ sudo docker-compose up --build
Building portfinance-liquidator
Step 1/10 : FROM node:alpine3.14 as builder
 ---> e32df7d6c22c
Step 2/10 : RUN mkdir -p /app
 ---> Using cache
 ---> 5f63fb1cb88d
Step 3/10 : WORKDIR /app
 ---> Using cache
 ---> 5227e5285054
Step 4/10 : COPY . ./
 ---> Using cache
 ---> 3a1ea6662597
Step 5/10 : RUN yarn install
 ---> Using cache
 ---> 6dc2439e1f06

Step 6/10 : FROM node:alpine3.14
 ---> e32df7d6c22c
Step 7/10 : USER node
 ---> Using cache
 ---> 44c68d5db061
Step 8/10 : COPY --from=builder /app /app
 ---> Using cache
 ---> fd23197b6c1c
Step 9/10 : WORKDIR /app
 ---> Using cache
 ---> fa8e9d4ece75
Step 10/10 : ENTRYPOINT [ "yarn", "liquidator" ]
 ---> Using cache
 ---> b92b9f275610

Successfully built b92b9f275610
Successfully tagged portfinance-liquidator:latest
Starting liquidator_portfinance-liquidator_1 ... done
Attaching to liquidator_portfinance-liquidator_1
portfinance-liquidator_1  | yarn run v1.22.17
portfinance-liquidator_1  | $ ts-node src/partial.ts
portfinance-liquidator_1  | Port liquidator launched on cluster=https://solana-api.projectserum.com
portfinance-liquidator_1  | Creating token account for PoRTjZMPXb9T7dyU7tpLEZRQj7e6ssfAE62j2oQuc6y
portfinance-liquidator_1  | Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
portfinance-liquidator_1  |
portfinance-liquidator_1  |
portfinance-liquidator_1  | /app/node_modules/@solana/web3.js/src/connection.ts:3575
portfinance-liquidator_1  |       throw new SendTransactionError(
portfinance-liquidator_1  |             ^
portfinance-liquidator_1  | Error: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
portfinance-liquidator_1  |     at Connection.sendEncodedTransaction (/app/node_modules/@solana/web3.js/src/connection.ts:3575:13)
portfinance-liquidator_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
portfinance-liquidator_1  |     at Connection.sendRawTransaction (/app/node_modules/@solana/web3.js/src/connection.ts:3535:20)
portfinance-liquidator_1  |     at Object.sendAndConfirmRawTransaction (/app/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
portfinance-liquidator_1  |     at sendTransaction (/app/src/utils.ts:188:12)
portfinance-liquidator_1  |     at Object.createAssociatedTokenAccount (/app/src/utils.ts:141:3)
portfinance-liquidator_1  |     at prepareTokenAccounts (/app/src/partial.ts:134:29)
portfinance-liquidator_1  |     at runLiquidator (/app/src/partial.ts:73:19)
portfinance-liquidator_1  | error Command failed with exit code 1.
portfinance-liquidator_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by leonardgee** [comment]
Hey @JiaxingZhao , thanks for filing this issue. I think this is likely caused by the `id.json` file that you provided is incorrect or doesn't have SOL in it. Can you let me know the `publicKey` that you have been using when running liquidators?
