### ISSUE TITLE
Liquidity amount provided cannot be zero

### ISSUE THREAD

**Issue by damru** [port-finance/liquidator#7]
Account has 0.15 SOL and 50 USDC

Error log:

```
Total number of obligations are: 1342,
The highest risk factors are: 1.0056,1.0024,0.9925,0.9553,0.9509,0.9466,0.9442,0.9440,0.9431,0.9431,
Borrow amount: 544.16,19977.80,6.16,17299.28,16.07,4929.22,490.22,0.89,64.58,17.00
Deposit value: 541.15,19930.57,6.21,18108.40,16.90,5207.42,519.20,0.95,68.48,18.03
Borrow assets: [USDT],[USDC],[PAI],[USDC],[USDC,USDT],[USDC,PAI],[SOL,USDC],[SOL],[USDC],[USDC]
Deposit assets: [MER],[MER],[MER],[MER,USDC],[SOL],[SOL,SRM,MER],[PAI,SOL,USDC],[USDC,SOL],[USDC],[USDC]
Obligation pubkey: [7P2z9kH1Rp9yiucGHnCx2KagtDK9enVQhW1gvbiVa79t],[8E5VtFvKF8SMuyhtwUCRiWDpKwFbssTG9vQLiwmbBev5],[4nJDABrstUDXfGTjvPiphZa9aooA3GZ9sPaz8hpp4Uqv],[8ewbuMNegBFbdWgw1xyNUBNDh8sLhEw7uLZ7pwGgpkbx],[3VYxAzL1Y82aGuMC2yiQcDFoRV8Ja3EQFQeAHZbwu2S2],[52gGBeUrXAfYAhCNjJG9NK3VmDE1Gi43WPVkGKRNd7d9],[E4rhuGERJUBMHd6xtiMdptYASxKeQBSrU4JBDMDV5M4K],[3oaUh7UD7cGgqmXdJb5L5NVVEUL6yN92i3vgaNQtFNog],[47hAaj8uxVSxGQ1txTBVEDUQpkQmDykGVnK5KgJU2184],[6D65WTGTpjTHK94TcTyuCV7g4rY6sWhhNCq3HBBvr37o]

name: USDT price: 1.00010932
name: PAI price: 1
name: SRM price: 6.403315800000001
name: BTC price: 47334.372
name: SOL price: 69.33148200000001
name: MER price: 0.5220287100000001
name: USDC price: 1

Time: Wed Aug 25 2021 09:05:12 GMT+0000 (Coordinated Universal Time) - payer account Ez6QfAqwDH3JBMKwZHHmJi7f9jheqyX8zaESdX32y2Xr, we have 2 accounts for liquidation
Liquidating obligation account 7P2z9kH1Rp9yiucGHnCx2KagtDK9enVQhW1gvbiVa79t which is owned by 2CyedV8gPjSU3kUgiFVG5oTiyK2N9qTVQb9d69RsZ6dQ with risk factor: 1.0055668917044098
which has borrowed 544.162681361824 with liquidation borrowed value at 599091667348051048428 ...

Transaction simulation failed: Error processing Instruction 4: custom program error: 0xa
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Refresh Reserve
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 22354 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Refresh Reserve
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 22399 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Refresh Obligation
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 21630 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
Program log: Instruction: Approve
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2434 of 200000 compute units
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Liquidate Obligation
Program log: Liquidity amount provided cannot be zero
Program log: Input amount is invalid
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 4207 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR failed: custom program error: 0xa

unknown error: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0xa

SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0xa
at Connection.sendEncodedTransaction (/app/liquidator/node_modules/@solana/web3.js/src/connection.ts:3575:13)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at Connection.sendRawTransaction (/app/liquidator/node_modules/@solana/web3.js/src/connection.ts:3535:20)
at Connection.sendTransaction (/app/liquidator/node_modules/@solana/web3.js/src/connection.ts:3523:12)
at liquidateAccount (/app/liquidator/src/partial-pyth.ts:261:15)
at runPartialLiquidator (/app/liquidator/src/partial-pyth.ts:66:9) {
logs: [
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Refresh Reserve',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 22354 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Refresh Reserve',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 22399 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Refresh Obligation',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 21630 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
'Program log: Instruction: Approve',
'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2434 of 200000 compute units',
'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Liquidate Obligation',
'Program log: Liquidity amount provided cannot be zero',
'Program log: Input amount is invalid',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 4207 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR failed: custom program error: 0xa'
]
}

```

**Comment by leonardgee** [comment]
Just checking, do you have enough tokens to repay the loan? It could be caused by you don't have a specific tokens.

**Comment by damru** [comment]
As specified I only have 50 USDC on the account and a few SOL
No other tokens beside that. 
So it could be because I dont have the same token as the loan, or it's not possible to liquidate only a fraction of the loan

**Comment by damru** [comment]
I just added some USDT and PAI and I cant see this issue anymore for now, just the https://github.com/port-finance/liquidator/issues/8
