### ISSUE TITLE
Cannot liquidate healthy obligations

### ISSUE THREAD

**Issue by damru** [port-finance/liquidator#8]
Account has 0.15 SOL and 50 USDC

Error log:

```
Total number of obligations are: 1328,
The highest risk factors are: 1.0065,1.0055,1.0024,0.9925,0.9874,0.9678,0.9590,0.9553,0.9487,0.9442,
Borrow amount: 4928.33,544.15,19977.80,6.16,16.07,54925.62,5.54,17299.28,159.57,490.07
Deposit value: 4896.45,541.15,19930.65,6.21,16.27,56755.12,5.78,18108.41,168.19,519.06
Borrow assets: [USDC,PAI],[USDT],[USDC],[PAI],[USDC,USDT],[USDC],[USDC],[USDC],[USDC,USDT],[SOL,USDC]
Deposit assets: [SOL,SRM,MER],[MER],[MER],[MER],[SOL],[SOL],[PAI,SOL,MER],[MER,USDC],[SOL],[PAI,SOL,USDC]
Obligation pubkey: [52gGBeUrXAfYAhCNjJG9NK3VmDE1Gi43WPVkGKRNd7d9],[7P2z9kH1Rp9yiucGHnCx2KagtDK9enVQhW1gvbiVa79t],[8E5VtFvKF8SMuyhtwUCRiWDpKwFbssTG9vQLiwmbBev5],[4nJDABrstUDXfGTjvPiphZa9aooA3GZ9sPaz8hpp4Uqv],[3VYxAzL1Y82aGuMC2yiQcDFoRV8Ja3EQFQeAHZbwu2S2],[A76mr2JetLiFrJUkrF9ds8BnymkS4MMLQtUKVBCfPvuV],[Dieq9YA7qLKDr9ktjzdYhTdz2gCSDLKYX6nASxoraDdj],[8ewbuMNegBFbdWgw1xyNUBNDh8sLhEw7uLZ7pwGgpkbx],[2gpPnEVbbGWPANMK4uJreiB97CwgmWwASXvCMNKQAwFE],[E4rhuGERJUBMHd6xtiMdptYASxKeQBSrU4JBDMDV5M4K]

name: USDC price: 1
name: SOL price: 66.770649
name: MER price: 0.52203095
name: SRM price: 6.3967989
name: PAI price: 1
name: USDT price: 1.00007928
name: BTC price: 48295.987

Time: Wed Aug 25 2021 09:01:59 GMT+0000 (Coordinated Universal Time) - payer account Ez6QfAqwDH3JBMKwZHHmJi7f9jheqyX8zaESdX32y2Xr, we have 3 accounts for liquidation
Liquidating obligation account 52gGBeUrXAfYAhCNjJG9NK3VmDE1Gi43WPVkGKRNd7d9 which is owned by CNJoPaegvCUpYB3ZT6WzJ3LAzDytUB3JoujnskbNGCgx with risk factor: 1.0065092998747287
which has borrowed 4928.327 with liquidation borrowed value at 5572727747142572594709 ...
unknown error: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 7: custom program error: 0x1d

Transaction simulation failed: Error processing Instruction 7: custom program error: 0x1d
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Refresh Reserve
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 18968 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Refresh Reserve
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 19018 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Refresh Reserve
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 20924 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Refresh Reserve
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 20931 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Refresh Reserve
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 21005 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Refresh Obligation
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 52264 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
Program log: Instruction: Approve
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2434 of 200000 compute units
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
Program log: Instruction: Liquidate Obligation
Program log: Obligation is healthy and cannot be liquidated
Program log: Cannot liquidate healthy obligations
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 10003 of 200000 compute units
Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR failed: custom program error: 0x1d
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 7: custom program error: 0x1d
at Connection.sendEncodedTransaction (/app/liquidator/node_modules/@solana/web3.js/src/connection.ts:3575:13)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at Connection.sendRawTransaction (/app/liquidator/node_modules/@solana/web3.js/src/connection.ts:3535:20)
at Connection.sendTransaction (/app/liquidator/node_modules/@solana/web3.js/src/connection.ts:3523:12)
at liquidateAccount (/app/liquidator/src/partial-pyth.ts:261:15)
at runPartialLiquidator (/app/liquidator/src/partial-pyth.ts:66:9) {
logs: [
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Refresh Reserve',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 18968 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Refresh Reserve',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 19018 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Refresh Reserve',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 20924 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Refresh Reserve',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 20931 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Refresh Reserve',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 21005 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Refresh Obligation',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 52264 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
'Program log: Instruction: Approve',
'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2434 of 200000 compute units',
'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
'Program log: Instruction: Liquidate Obligation',
'Program log: Obligation is healthy and cannot be liquidated',
'Program log: Cannot liquidate healthy obligations',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 10003 of 200000 compute units',
'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR failed: custom program error: 0x1d'
]
}
```

**Comment by leonardgee** [comment]
This can occur when someone has already liquidate the bad debt.

**Comment by drubio-tlnd** [comment]
It's happening on the same multiple times.
Looking at the logs I could see that the risk factor was moving to >1 and <1 very quickly

**Comment by damru** [comment]
It's happening on the same multiple times.
Looking at the logs I could see that the risk factor was moving to >1 and <1 very quickly

**Comment by damru** [comment]
Keep having this issue after adding USDT and PAI

**Comment by leonardgee** [comment]
The frequency that you encounter the issue should be reduced since we have switched to use the `Big.js` package instead of the JS native `number` type. However you might still encounter this when there is price change between the point you send the transaction to the point when the transaction is processed.
