### ISSUE TITLE
Deposit reserve of collateral 0 does not match the deposit reserve provided

### ISSUE THREAD

**Issue by damru** [port-finance/liquidator#9]
Account has some SOL, USDC, USDT, PAI, SRM

error log:
```
Total number of obligations are: 1550,
     The highest risk factors are: 1.0077,0.9826,0.9771,0.9766,0.9705,0.9678,0.9673,0.9610,0.9584,0.9570,
     Borrow amount: 3.64,0.71,236.17,23.62,4.72,1378.69,10.27,1.22,17308.18,0.71
     Deposit value: 3.62,0.72,241.70,24.18,4.87,1424.62,10.62,1.27,18059.75,0.74
     Borrow assets: [SOL],[SOL],[SOL],[SOL],[SOL],[SOL],[SRM],[SOL],[USDC],[SOL]
     Deposit assets: [SOL,PAI],[PAI],[USDT],[USDC],[PAI,SOL],[USDC,SOL],[PAI],[USDC,SOL],[MER,USDC],[PAI]
     Obligation pubkey: [FKwuZsRuJUysj2aW9MwhAiW9wgQ7exEEWWY6R5F4Tk7j],[BwrEBCZtZ3ENAmKQkcdMYzF4VwaRRDfQkUwKXtuC8JE4],[ELUPv1gDvcbQVF6JjSPoVpwqM5KVy5L5mfBpULMVSG5E],[6e6BueaRZ2kQ91dt1hTQmHRFjiLgeyms8FH3XdB2fhtT],[CJLPbuqok9abBjrFZ4ryuKAhcdsYrFdquPEusa1whLa9],[6mLnC3g7AciDz1t192rpgRburtDMrwnyLmwmFsu1ndza],[HYmpZ1K6JFam5K4h7ynUrVyDaawDZfZvjxqdosBxoM8D],[3oaUh7UD7cGgqmXdJb5L5NVVEUL6yN92i3vgaNQtFNog],[8ewbuMNegBFbdWgw1xyNUBNDh8sLhEw7uLZ7pwGgpkbx],[DWHyDNdzvR5p5KuX84UtF2VirmCqh7653vWP7gYXwvDf]

name: SOL price: 94.4265
name: PAI price: 1
name: BTC price: 48826.195
name: USDT price: 1.0005
name: MER price: 0.5118670200000001
name: USDC price: 1
name: SRM price: 7.9396941000000005
name: undefined price: 94.4265

Time: Sat Aug 28 2021 12:13:04 GMT+0000 (Coordinated Universal Time) - payer account Ez6QfAqwDH3JBMKwZHHmJi7f9jheqyX8zaESdX32y2Xr, we have 1 accounts for liquidation
 Liquidating obligation account FKwuZsRuJUysj2aW9MwhAiW9wgQ7exEEWWY6R5F4Tk7j which is owned by 9Ms9N8QcpbcMzvu5hFMsB88MTT72ZA6gpWEkCmto1NHY with risk factor: 1.0076534399356505
           which has borrowed 3.6448629000000006 with liquidation borrowed value at 6391566230217205379 ...
Transaction simulation failed: Error processing Instruction 4: custom program error: 0xd 
    Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
    Program log: Instruction: Refresh Reserve
    Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 22312 of 200000 compute units
    Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
    Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
    Program log: Instruction: Refresh Reserve
    Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 19060 of 200000 compute units
unknown error: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0xd
    Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
    Program log: Instruction: InitializeAccount
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3680 of 200000 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]
    Program log: Instruction: Refresh Obligation
    Program log: Deposit reserve of collateral 0 does not match the deposit reserve provided
    Program log: Invalid account input
    Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 4871 of 200000 compute units
    Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR failed: custom program error: 0xd
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0xd
    at Connection.sendEncodedTransaction (/app/node_modules/@solana/web3.js/src/connection.ts:3575:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Connection.sendRawTransaction (/app/node_modules/@solana/web3.js/src/connection.ts:3535:20)
    at Connection.sendTransaction (/app/node_modules/@solana/web3.js/src/connection.ts:3523:12)
    at liquidateAccount (/app/src/partial-pyth.ts:261:15)
    at runPartialLiquidator (/app/src/partial-pyth.ts:66:9) {

[
    'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
    'Program log: Instruction: Refresh Reserve',
    'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 22312 of 200000 compute units',
    'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
    'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
    'Program log: Instruction: Refresh Reserve',
    'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 19060 of 200000 compute units',
    'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR success',
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Instruction: InitializeAccount',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3680 of 200000 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR invoke [1]',
    'Program log: Instruction: Refresh Obligation',
    'Program log: Deposit reserve of collateral 0 does not match the deposit reserve provided',
    'Program log: Invalid account input',
    'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR consumed 4871 of 200000 compute units',
    'Program Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR failed: custom program error: 0xd'
  ]
}
```

**Comment by leonardgee** [comment]
This should be transient. The error occurs when users adds more asset as collateral to Port on top of their existing assets.

**Comment by damru** [comment]
Ok but why do I keep having this same issue with the exact same liquidation account ? Still now I keep having this issue

**Comment by leonardgee** [comment]
Are you still seeing the issue when you run the liquidator?

**Comment by leonardgee** [comment]
This should be transient. This occurs when users have deposit additional collateral after the liquidator has obtained the on-chain state. It should recover itself in the next iteration of the loop.
